from collections.abc import Mapping

def bind_runtime(namespace: Mapping[str, object]) -> None: ...

from .content_selection import (
    _normalize_anthropic_google_completion_adapter_model_name as _normalize_anthropic_google_completion_adapter_model_name,
    _normalize_codex_google_code_assist_adapter_model_name as _normalize_codex_google_code_assist_adapter_model_name,
    _extract_google_adapter_agent_name_from_completion_messages as _extract_google_adapter_agent_name_from_completion_messages,
    _extract_google_adapter_latest_user_prompt_text as _extract_google_adapter_latest_user_prompt_text,
    _extract_google_adapter_latest_tool_result_fingerprint as _extract_google_adapter_latest_tool_result_fingerprint,
    _estimate_google_content_text_chars as _estimate_google_content_text_chars,
    _selected_google_contents_have_paired_function_responses as _selected_google_contents_have_paired_function_responses,
    _selected_google_contents_have_complete_function_exchanges as _selected_google_contents_have_complete_function_exchanges,
    _add_required_google_function_call_pair_indices as _add_required_google_function_call_pair_indices,
    _trim_google_content_indices_to_window as _trim_google_content_indices_to_window,
    _trim_google_adapter_followup_tools as _trim_google_adapter_followup_tools,
    _is_google_function_call_allowed_predecessor as _is_google_function_call_allowed_predecessor,
    _merge_google_model_content_parts as _merge_google_model_content_parts,
    _repair_google_adapter_function_call_turn_adjacency as _repair_google_adapter_function_call_turn_adjacency,
)

from .content_compaction import (
    _split_google_adapter_inline_context_and_prompt as _split_google_adapter_inline_context_and_prompt,
    _compact_google_adapter_oversized_text_part as _compact_google_adapter_oversized_text_part,
    _compact_google_adapter_oversized_text_parts as _compact_google_adapter_oversized_text_parts,
    _apply_google_adapter_contents_window_policy as _apply_google_adapter_contents_window_policy,
    _apply_google_adapter_generation_config_policy as _apply_google_adapter_generation_config_policy,
    _apply_google_adapter_request_shape_policy as _apply_google_adapter_request_shape_policy,
)

from .error_and_schema import (
    _extract_google_adapter_exception_status_code as _extract_google_adapter_exception_status_code,
    _extract_google_adapter_exception_detail as _extract_google_adapter_exception_detail,
    _extract_google_adapter_error_payloads as _extract_google_adapter_error_payloads,
    _extract_google_adapter_error_reason as _extract_google_adapter_error_reason,
    _extract_google_adapter_error_payload_for_logging as _extract_google_adapter_error_payload_for_logging,
    _is_google_adapter_transient_retryable_failure as _is_google_adapter_transient_retryable_failure,
    _build_google_adapter_terminal_error_log_context as _build_google_adapter_terminal_error_log_context,
    _normalize_google_completion_adapter_model_name as _normalize_google_completion_adapter_model_name,
    _sanitize_google_schema_array_items as _sanitize_google_schema_array_items,
    _merge_google_code_assist_schema_annotations as _merge_google_code_assist_schema_annotations,
    _sanitize_google_code_assist_union_schemas as _sanitize_google_code_assist_union_schemas,
    _sanitize_google_code_assist_tool_schema as _sanitize_google_code_assist_tool_schema,
)

from .schema_and_prompt import (
    _is_google_adapter_synthetic_tool_context_text as _is_google_adapter_synthetic_tool_context_text,
    _is_google_adapter_synthetic_tool_context_message as _is_google_adapter_synthetic_tool_context_message,
    _inject_google_adapter_fallback_text_context as _inject_google_adapter_fallback_text_context,
    _extract_google_adapter_system_text_from_content as _extract_google_adapter_system_text_from_content,
    _replace_google_adapter_system_message_text as _replace_google_adapter_system_message_text,
    _append_codex_google_code_assist_tool_contract_to_system_text as _append_codex_google_code_assist_tool_contract_to_system_text,
    _apply_codex_google_code_assist_tool_contract_policy as _apply_codex_google_code_assist_tool_contract_policy,
    _is_google_adapter_claude_overhead_block as _is_google_adapter_claude_overhead_block,
    _strip_google_adapter_claude_system_overhead as _strip_google_adapter_claude_system_overhead,
    _build_google_adapter_system_prompt_policy_text as _build_google_adapter_system_prompt_policy_text,
    _apply_google_adapter_system_prompt_policy as _apply_google_adapter_system_prompt_policy,
)

from .anthropic_replay import (
    _normalize_codex_openai_chat_kwargs_for_google_code_assist as _normalize_codex_openai_chat_kwargs_for_google_code_assist,
    _has_codex_google_code_assist_anthropic_tool_replay_blocks as _has_codex_google_code_assist_anthropic_tool_replay_blocks,
    _normalize_codex_google_code_assist_anthropic_assistant_message as _normalize_codex_google_code_assist_anthropic_assistant_message,
    _normalize_codex_google_code_assist_anthropic_user_message as _normalize_codex_google_code_assist_anthropic_user_message,
    _build_codex_google_code_assist_anthropic_replay_changes as _build_codex_google_code_assist_anthropic_replay_changes,
    _normalize_codex_google_code_assist_anthropic_tool_replay as _normalize_codex_google_code_assist_anthropic_tool_replay,
    _deterministic_codex_google_code_assist_tool_call_id as _deterministic_codex_google_code_assist_tool_call_id,
    _next_codex_google_code_assist_tool_messages as _next_codex_google_code_assist_tool_messages,
    _paired_codex_google_code_assist_tool_message as _paired_codex_google_code_assist_tool_message,
    _repair_codex_google_code_assist_tool_call_id as _repair_codex_google_code_assist_tool_call_id,
    _repair_codex_google_code_assist_openai_tool_call_ids as _repair_codex_google_code_assist_openai_tool_call_ids,
)

from .tool_pairing import (
    _normalize_codex_google_code_assist_reasoning_effort as _normalize_codex_google_code_assist_reasoning_effort,
    _normalize_google_code_assist_thinking_max_tokens as _normalize_google_code_assist_thinking_max_tokens,
    _normalize_codex_google_code_assist_tool_call_arguments as _normalize_codex_google_code_assist_tool_call_arguments,
    _infer_single_codex_google_code_assist_function_tool_name as _infer_single_codex_google_code_assist_function_tool_name,
    _is_codex_google_code_assist_empty_text_content as _is_codex_google_code_assist_empty_text_content,
    _previous_codex_google_code_assist_assistant_index as _previous_codex_google_code_assist_assistant_index,
    _previous_codex_google_code_assist_contiguous_assistant_index as _previous_codex_google_code_assist_contiguous_assistant_index,
    _previous_codex_google_code_assist_tool_call as _previous_codex_google_code_assist_tool_call,
    _build_codex_google_code_assist_synthetic_tool_call as _build_codex_google_code_assist_synthetic_tool_call,
    _append_codex_google_code_assist_tool_call_to_assistant as _append_codex_google_code_assist_tool_call_to_assistant,
    _build_codex_google_code_assist_tool_pair_repair_changes as _build_codex_google_code_assist_tool_pair_repair_changes,
    _append_codex_google_code_assist_orphan_tool_result_context as _append_codex_google_code_assist_orphan_tool_result_context,
    _sanitize_codex_google_code_assist_orphan_tool_results as _sanitize_codex_google_code_assist_orphan_tool_results,
    _ensure_codex_google_code_assist_tool_results_have_calls as _ensure_codex_google_code_assist_tool_results_have_calls,
)

from .request_assembly import (
    _build_google_code_assist_request_from_completion_kwargs as _build_google_code_assist_request_from_completion_kwargs,
)

from .request_building import (
    _drop_codex_google_code_assist_non_function_tools as _drop_codex_google_code_assist_non_function_tools,
    _build_codex_google_code_assist_completion_kwargs as _build_codex_google_code_assist_completion_kwargs,
    _prepare_codex_google_code_assist_adapter_request as _prepare_codex_google_code_assist_adapter_request,
)

from .tool_aliasing import (
    _apply_google_code_assist_alias_to_function_block as _apply_google_code_assist_alias_to_function_block,
    _apply_google_code_assist_alias_to_tool as _apply_google_code_assist_alias_to_tool,
    _apply_google_code_assist_aliases_to_tool_calls as _apply_google_code_assist_aliases_to_tool_calls,
    _apply_google_code_assist_aliases_to_message as _apply_google_code_assist_aliases_to_message,
    _apply_google_code_assist_native_tool_aliases as _apply_google_code_assist_native_tool_aliases,
    _inject_google_adapter_tool_call_context_text as _inject_google_adapter_tool_call_context_text,
    _extract_google_adapter_preserved_task_excerpt as _extract_google_adapter_preserved_task_excerpt,
    _build_google_adapter_preserved_task_state_message as _build_google_adapter_preserved_task_state_message,
    _apply_google_adapter_completion_message_window as _apply_google_adapter_completion_message_window,
    _normalize_google_code_assist_httpx_payload as _normalize_google_code_assist_httpx_payload,
    _annotate_google_code_assist_duplicate_tool_response_parts as _annotate_google_code_assist_duplicate_tool_response_parts,
    _annotate_google_code_assist_duplicate_tool_responses as _annotate_google_code_assist_duplicate_tool_responses,
    _annotate_google_code_assist_claude_tool_response_ids as _annotate_google_code_assist_claude_tool_response_ids,
    _insert_google_code_assist_missing_claude_function_call_pairs as _insert_google_code_assist_missing_claude_function_call_pairs,
)

from .response_translation import (
    _extract_google_code_assist_text_metrics as _extract_google_code_assist_text_metrics,
    _summarize_google_code_assist_content_preview_entry as _summarize_google_code_assist_content_preview_entry,
    _summarize_google_code_assist_request_contents_shape as _summarize_google_code_assist_request_contents_shape,
    _summarize_google_code_assist_generation_config_shape as _summarize_google_code_assist_generation_config_shape,
    _extract_google_code_assist_function_names as _extract_google_code_assist_function_names,
    _summarize_google_code_assist_request_shape as _summarize_google_code_assist_request_shape,
    _unwrap_google_code_assist_response_payload as _unwrap_google_code_assist_response_payload,
    _translate_google_code_assist_response_to_anthropic as _translate_google_code_assist_response_to_anthropic,
)

from .response_streaming import (
    _iterate_google_code_assist_unwrapped_stream as _iterate_google_code_assist_unwrapped_stream,
    _build_anthropic_streaming_response_from_google_code_assist_stream as _build_anthropic_streaming_response_from_google_code_assist_stream,
    _restore_google_adapter_tool_call_names as _restore_google_adapter_tool_call_names,
    _restore_google_adapter_tool_call_names_stream as _restore_google_adapter_tool_call_names_stream,
    _collect_google_code_assist_model_response_from_stream as _collect_google_code_assist_model_response_from_stream,
    _collect_google_code_assist_response_from_stream as _collect_google_code_assist_response_from_stream,
    _build_codex_streaming_response_from_google_code_assist_stream as _build_codex_streaming_response_from_google_code_assist_stream,
    _build_google_debug_header_summary as _build_google_debug_header_summary,
    _build_google_adapter_native_headers as _build_google_adapter_native_headers,
    _is_codex_google_code_assist_empty_success_model_response as _is_codex_google_code_assist_empty_success_model_response,
    _sanitize_google_code_assist_request_schemas as _sanitize_google_code_assist_request_schemas,
)

from .request_preparation import (
    _prepare_anthropic_google_completion_adapter_request as _prepare_anthropic_google_completion_adapter_request,
)

from .persisted_output import (
    _compact_google_adapter_persisted_output_preview_and_expanded_text as _compact_google_adapter_persisted_output_preview_and_expanded_text,
    _compact_expanded_claude_persisted_output_text_for_google_adapter as _compact_expanded_claude_persisted_output_text_for_google_adapter,
    _compact_google_adapter_text_part_sequence as _compact_google_adapter_text_part_sequence,
    _compact_google_adapter_followup_request_contents as _compact_google_adapter_followup_request_contents,
    _compact_google_adapter_persisted_output_value as _compact_google_adapter_persisted_output_value,
    _compact_google_adapter_persisted_output_in_anthropic_request_body as _compact_google_adapter_persisted_output_in_anthropic_request_body,
)
